export const PROCESS_NAME = Object.freeze({
    START: "ProcessStart",
    MENU: "ProcessMenu",
    DETAILS: "ProcessDetails",
    PAYMENTS: "ProcessPayments",
    CARD_INSERT: "ProcessCardInsert",
    MOBILE_PAY: "ProcessMobilePay",
    SIMPLE_PAY: "ProcessSimplePay",
    CARD_REMOVAL: "ProcessCardRemoval",
    ORDER_COMPLETE: "ProcessOrderComplete",
    RECEIPT_PRINT: "ProcessReceiptPrint",
    FINISH: "ProcessFinish"
});

/** Backspace 시 역행할 이전 프로세스 */
export const PROCESS_PREV_BY_CURRENT = Object.freeze({
    [PROCESS_NAME.START]: null,
    [PROCESS_NAME.MENU]: PROCESS_NAME.START,
    [PROCESS_NAME.DETAILS]: PROCESS_NAME.MENU,
    [PROCESS_NAME.PAYMENTS]: PROCESS_NAME.DETAILS,
    [PROCESS_NAME.CARD_INSERT]: PROCESS_NAME.PAYMENTS,
    [PROCESS_NAME.MOBILE_PAY]: PROCESS_NAME.PAYMENTS,
    [PROCESS_NAME.SIMPLE_PAY]: PROCESS_NAME.PAYMENTS,
    [PROCESS_NAME.CARD_REMOVAL]: PROCESS_NAME.CARD_INSERT,
    [PROCESS_NAME.ORDER_COMPLETE]: PROCESS_NAME.PAYMENTS,
    [PROCESS_NAME.RECEIPT_PRINT]: PROCESS_NAME.ORDER_COMPLETE,
    [PROCESS_NAME.FINISH]: PROCESS_NAME.RECEIPT_PRINT
});

export const STEP_INDEX_BY_PROCESS = Object.freeze({
    [PROCESS_NAME.MENU]: 1,
    [PROCESS_NAME.DETAILS]: 2,
    [PROCESS_NAME.PAYMENTS]: 3,
    [PROCESS_NAME.CARD_INSERT]: 3,
    [PROCESS_NAME.MOBILE_PAY]: 3,
    [PROCESS_NAME.SIMPLE_PAY]: 3,
    [PROCESS_NAME.CARD_REMOVAL]: 3,
    [PROCESS_NAME.ORDER_COMPLETE]: 4,
    [PROCESS_NAME.RECEIPT_PRINT]: 4,
    [PROCESS_NAME.FINISH]: 5
});
