import React from "react";

const MODAL_CONFIG = {
    deleteCheck: {
        tts: "알림, 주문없음, 주문이 없으면 메뉴선택으로 돌아갑니다, 실행하시려면 메뉴 버튼을 누릅니다, ",
        icon: "GraphicWarning",
        title: "주문없음",
        cancelIcon: "Cancel",
        cancelLabel: "취소",
        confirmIcon: "Add",
        confirmLabel: "메뉴",
        message: <><span>주문이 없으면 <span className="primary">메뉴선택</span>으로 돌아갑니다</span><span>실행하시려면 <span className="primary">메뉴</span> 버튼을 누릅니다</span></>,
    },
    delete: {
        tts: "알림, 상품삭제, 주문 상품을 삭제합니다, 실행하시려면 삭제 버튼을 누릅니다, ",
        icon: "GraphicTrash",
        title: "삭제",
        cancelIcon: "Cancel",
        cancelLabel: "취소",
        confirmIcon: "Delete",
        confirmLabel: "삭제",
        message: <><span>주문 상품을 <span className="primary">삭제</span>합니다</span><span>실행하시려면 <span className="primary">삭제</span> 버튼을 누릅니다</span></>,
    },
    reselect: {
        tts: "알림, 비우기, 주문 내역을 비웁니다, 실행하시려면 비우기 버튼을 누릅니다, ",
        icon: "GraphicReset",
        title: "비우기",
        cancelIcon: "Cancel",
        cancelLabel: "취소",
        confirmIcon: "Reset",
        confirmLabel: "비우기",
        message: <><span>주문 내역을 <span className="primary">비웁니다</span></span><span>실행하시려면 <span className="primary">비우기</span> 버튼을 누릅니다</span></>,
    },
    restart: {
        tts: "알림, 처음으로, 처음으로 이동합니다, 실행하시려면 처음으로 버튼을 누릅니다,",
        icon: "GraphicHome",
        title: "처음으로",
        cancelIcon: "Cancel",
        cancelLabel: "취소",
        confirmIcon: "Ok",
        confirmLabel: "처음으로",
        message: <><span><span className="primary">처음으로</span> 이동합니다</span><span>실행하시려면 <span className="primary">처음으로</span> 버튼을 누릅니다</span></>,
    },
    call: {
        tts: "알림, 직원 호출, 직원을 호출합니다, 실행하시려면 호출 버튼을 누릅니다,",
        icon: "GraphicBell",
        title: "직원 호출",
        cancelIcon: "Cancel",
        cancelLabel: "취소",
        confirmIcon: "GraphicBell",
        confirmLabel: "호출",
        message: <><span>직원을 <span className="primary">호출</span>합니다</span><span>실행하시려면 <span className="primary">호출</span> 버튼을 누릅니다</span></>,
    },
    timeout: {
        tts: "알림, 시간연장, 사용시간이 20초 남았습니다, 계속 사용하시려면 연장 버튼을 누릅니다, ",
        icon: "Extention",
        title: "시간연장",
        cancelIcon: "Home",
        cancelLabel: "시작화면",
        confirmIcon: "Extention",
        confirmLabel: "연장",
        message: (countdown) => <><span>사용시간이 <span className="primary">{countdown !== undefined ? `${Math.ceil(countdown / 1000)}초` : '20초'}</span> 남았습니다</span><span>계속 사용하시려면 <span className="primary">연장</span> 버튼을 누릅니다</span></>,
    },
    paymentError: {
        tts: "알림, 결제 경고, 카드가 잘못 삽입되었습니다, 카드를 제거하시고 다시 결제 버튼을 누릅니다, ",
        icon: "GraphicWarning",
        title: "결제 경고",
        cancelIcon: null,
        cancelLabel: null,
        confirmIcon: "Warning",
        confirmLabel: "다시 결제",
        confirmButtonStyle: "delete",
        message: <><span>카드가 <span className="primary">잘못 삽입</span>되었습니다</span><span>카드를 제거하시고 <span className="primary">다시 결제</span> 버튼을 누릅니다</span></>,
    },
    accessibility: {
        tts: "알림, 접근성, 원하시는 접근성 옵션을 선택하시고, 적용하기 버튼을 누릅니다, ",
        icon: "Wheelchair",
        title: "접근성",
        cancelIcon: "Cancel",
        cancelLabel: "적용안함",
        confirmIcon: "Ok",
        confirmLabel: "적용하기",
        message: <><span>원하시는 <span className="primary">접근성 옵션</span>을 선택하시고</span><span><span className="primary">적용하기</span> 버튼을 누릅니다</span></>,
    },
};

export default MODAL_CONFIG;
